### PR TITLE
Transition to Ruby implementation

### LINKED ISSUE #77: Consider a Ruby Implementation
As this project mostly wraps calls out `docker-compose` with a little extra sugar it's made sense to be written strictly in bash. However as more options and support for arguments are added the [conditional logic and string based "templating"](https://github.com/technekes/nib/blob/master/bin/console) has caused the scripts become harder to write and maintain. As this project is written by Ruby developers and bash scripting novices it makes sense to consider replacing bash with Ruby or some mixture of the two. 

There are a great number of option parsing ([OptionParser](http://ruby-doc.org/stdlib-2.3.1/libdoc/optparse/rdoc/OptionParser.html), [Trollop](http://manageiq.github.io/trollop/)) and command line frameworks ([rake](https://github.com/ruby/rake), [thor](http://whatisthor.com/)) available for Ruby. Here is a thorough (up to date) list of available tools compiled [here](http://www.awesomecommandlineapps.com/gems.html).

Should #74 (project templates etc) be adopted then the idea of using Ruby becomes even more palatable.

### PR DESCRIPTION
**Pull request by johnallen3d**
Commands to be implemented:

* ~~console~~
* ~~debug~~
* ~~setup~~
* ~~shell~~

Additional internal updates:

* ~~check for update~~
* ~~Use Ruby to create `docs/commands.md`~~
* ~~Convert release script to a binstub~~

This PR should no longer be considered a work in progress.

Resolves #77

### CODE REVIEW

**Comment by blankenshipz** [comment]
@johnallen3d Have you done any `benchmarks`? I'd be interested to know what the overhead of the RVM is compared to the bash approach. 

Something simple like `time nib run web true` should give a decent approximation

**Comment by johnallen3d** [comment]
Good question @blankenshipz! Here's are a couple of `time`'d commands for `nib` (bash) and `nibdev` (Ruby):

```sh
❯ time nib run web true
shell  1.83s user 1.37s system 0% cpu 15:50:56.74 total
children  2.96s user 2.78s system 0% cpu 15:50:56.74 total

❯ time nib run web true
shell  1.84s user 1.38s system 0% cpu 15:51:01.24 total
children  2.98s user 2.80s system 0% cpu 15:51:01.24 total

❯ time nibdev run web true
shell  1.79s user 1.34s system 0% cpu 15:50:40.43 total
children  2.92s user 2.71s system 0% cpu 15:50:40.43 total

❯ time nibdev run web true
shell  1.81s user 1.35s system 0% cpu 15:50:46.63 total
children  2.94s user 2.75s system 0% cpu 15:50:46.63 total
```

If that's valid then Ruby is slightly faster?!? 😲

**Comment by blankenshipz** [comment]
👏 👏

**Comment by johnallen3d** [comment]
These commits were squashed and merged into master as f9e7f2d081ead9c7a210f73a7bb112376b9230a4.

**Pull request closed without merging**
