### PR TITLE
Upgrade docker components

### PR DESCRIPTION
**Pull request by blankenshipz**
Upgrades `docker-compose` to `1.7.0` and removes the dependency `docker` engine

:eyes: @johnallen3d

### CODE REVIEW

**Comment by johnallen3d** [comment]
Yay, removing a dependency! 👍

**Comment by johnallen3d** [comment]
Uh oh, @blankenshipz: https://github.com/technekes/nib/blob/master/script/update#L5

**Comment by blankenshipz** [comment]
@johnallen3d Interesting, I guess we need to decide if we'd like to reimplement this feature in a different way or reintroduce this dependency?

**Comment by johnallen3d** [comment]
The only alternative I can think of is something like when you start up a docker-machine. Essentially echo out the command and ask the user to copy/paste/execute. Or remove the feature and just update the README.md instructions. Which way do you lean?

**Comment by blankenshipz** [comment]
I'm not sure honestly, `docker-compose` does support `pull` but only for `services` (e.g defined in `docker-compose.yml`) Perhaps there's a way to add a `docker-compose.yml` to this project and have the `pull` reference that?

**Comment by johnallen3d** [comment]
Very clever, I'll give that a try.

**Pull request closed without merging**
