### PR TITLE
Adding an rspec shortcut

### PR DESCRIPTION
**Pull request by blankenshipz**
Creates an `rspec` helper following the defined pattern. 

Per #27

### CODE REVIEW

**Comment by blankenshipz** [comment]
@johnallen3d :eyes:

**Comment by johnallen3d** [comment]
Add the rspec command to `./bin/_help` and you're good to go!

**Comment by blankenshipz** [comment]
@johnallen3d new commits! :eyes:

**Comment by johnallen3d** [comment]
👍

**Pull request merged**
